name: ie-bank-infra

on:
  workflow_dispatch:
  push:
    branches:
      - "*" 
    paths:
      - "**"
      - "!scripts/**"
  pull_request:
    branches:
      - main 
    paths:
      - "**"
      - "!scripts/**"

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: pruizalliata
  ENV: development
  DBHOST: pruizalliata-dbsrv-dev.postgres.database.azure.com
  DBNAME: ie-bank-db
  FLASK_APP: app.py
  FLASK_DEBUG: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Bicep Linter
        run: az bicep build --file ./main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Variables
        run: |
          echo "ENV: ${{ env.ENV }}"
          echo "DBHOST: ${{ env.DBHOST }}"
          echo "DBNAME: ${{ env.DBNAME }}"
          echo "FLASK_APP: ${{ env.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ env.FLASK_DEBUG }}"

      - name: Deploy to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: |
            ./parameters/dev.parameters.json
            appServiceAPIEnvVarENV=${{ env.ENV }}
            appServiceAPIEnvVarDBHOST=${{ env.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ env.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIEnvVarDBUSER=${{ secrets.DBUSER }}
            appServiceAPIEnvVarFLASK_APP=${{ env.FLASK_APP }}
            appServiceAPIEnvVarFLASK_DEBUG=${{ env.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-deployment

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref == 'refs/heads/main' }}
    environment:
      name: "UAT"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Variables
        run: |
          echo "ENV: ${{ env.ENV }}"
          echo "DBHOST: ${{ env.DBHOST }}"
          echo "DBNAME: ${{ env.DBNAME }}"
          echo "FLASK_APP: ${{ env.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ env.FLASK_DEBUG }}"

      - name: Deploy to UAT
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: |
            ./parameters/uat.parameters.json
            appServiceAPIEnvVarENV=${{ env.ENV }}
            appServiceAPIEnvVarDBHOST=${{ env.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ env.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIEnvVarDBUSER=${{ secrets.DBUSER }}
            appServiceAPIEnvVarFLASK_APP=${{ env.FLASK_APP }}
            appServiceAPIEnvVarFLASK_DEBUG=${{ env.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-uat
